Repository eyupbarlas/JavaReactFullStackApp, pull requests merged in 2024-01, with the labels that each got.

#15 added values into applicationyaml
  java-backend/src/main/resources/application.properties
Labels: need review

#16 Adding REST Controllers
  java-backend/src/main/java/com/backend/javabackend/constants/FullStackAppConstants.java
  java-backend/src/main/java/com/backend/javabackend/rest/UserRest.java
Labels: need review, waiting for merge

#19 Create pull_request_template.md
  .github/pull_request_template.md
Labels: waiting for merge

#17 docker config with mysql and adminer
  docker-compose.yaml
  java-backend/src/main/resources/application.properties
  java-backend/src/main/resources/application.yaml
Labels: waiting for merge

#20 Update README.md
  README.md
Labels: waiting for merge

#18 Adding controllers and tests
  docker-compose.yaml
  java-backend/src/main/java/com/backend/javabackend/rest/UserRest.java
  java-backend/src/main/java/com/backend/javabackend/service/UserService.java
  java-backend/src/main/resources/application.yaml
  java-backend/src/test/java/com/backend/javabackend/repository/UserRepositoryTests.java
  java-backend/src/test/java/com/backend/javabackend/rest/UserRestTests.java
  java-backend/src/test/java/com/backend/javabackend/service/UserServiceTests.java
Labels: do not merge

#23 Adding service class
  java-backend/src/main/java/com/backend/javabackend/data/User.java
  java-backend/src/main/java/com/backend/javabackend/service/UserService.java
Labels: need review

#22 adding exception handling
  java-backend/src/main/java/com/backend/javabackend/exception/UserNotFoundAdvice.java
  java-backend/src/main/java/com/backend/javabackend/exception/UserNotFoundException.java
Labels: need review

#24 Implementing Rest Controllers
  java-backend/src/main/java/com/backend/javabackend/constants/FullStackAppConstants.java
  java-backend/src/main/java/com/backend/javabackend/data/UserResponse.java
  java-backend/src/main/java/com/backend/javabackend/exception/UserNotFoundException.java
  java-backend/src/main/java/com/backend/javabackend/repository/UserRepository.java
  java-backend/src/main/java/com/backend/javabackend/rest/UserRest.java
  java-backend/src/main/java/com/backend/javabackend/service/UserService.java
  java-backend/src/test/java/com/backend/javabackend/repository/UserRepositoryTests.java
  java-backend/src/test/java/com/backend/javabackend/service/UserServiceTests.java
Labels: need review

#36 Creating frontend file structure
  frontend/README.md
  frontend/fullstack-front-test/.gitignore
  frontend/fullstack-front-test/README.md
  frontend/fullstack-front-test/package-lock.json
  frontend/fullstack-front-test/package.json
  frontend/fullstack-front-test/public/favicon.ico
  frontend/fullstack-front-test/public/index.html
  frontend/fullstack-front-test/public/logo192.png
  frontend/fullstack-front-test/public/logo512.png
  frontend/fullstack-front-test/public/manifest.json
  frontend/fullstack-front-test/public/robots.txt
  frontend/fullstack-front-test/src/App.css
  frontend/fullstack-front-test/src/App.js
  frontend/fullstack-front-test/src/App.test.js
  frontend/fullstack-front-test/src/index.css
  frontend/fullstack-front-test/src/index.js
  frontend/fullstack-front-test/src/logo.svg
  frontend/fullstack-front-test/src/reportWebVitals.js
  frontend/fullstack-front-test/src/setupTests.js
Labels: need review
